name: tests
on: { workflow_dispatch, push: { paths-ignore: [ 'README.md', 'LICENSE' ] } }
# Configuration
env:
  strDirGTest: "ThirdParty"
  strTestExecutable: test.exe
jobs:
  build-tests-gtest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download googleTestLatestRepo
        # working-directory: ${{ env.strDirGTest }}
        id: download-gtest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: google/googletest
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Show log
          # echo "dir2"
          # dir ${{ env.strDirGTest }}
        run: | # pwsh
          echo "dir1"
          dir
          echo "steps.download-gtest.outputs. ..."
          echo "release=${{ steps.download-gtest.outputs.release }}"
          echo "id=${{ steps.download-gtest.outputs.id }}"
          echo "description=${{ steps.download-gtest.outputs.description }}"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      # - name: Build test
        # run: MSBuild test/test.sln -noLogo -verbosity:quiet -m -p:Platform=${env:strPlatform} -p:Configuration=${env:strConfiguration} 

      # - name: Run test
        # run: | # pwsh
          # $arglist="--logfile?"
          # $strResult = Start-Process -Wait -NoNewWindow "${{env.strTestExecutable}}"
