name: tests
on: { workflow_dispatch, push: { paths-ignore: [ 'README.md', 'LICENSE' ] } }
# Configuration
env:
  strDirGTest: "ThirdParty"
  strTestExecutable: test.exe
jobs:
  build-tests-gtest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download googleTestLatestRepo
        id: gtest-tag
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: google/googletest
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Show log 1
        run: | # pwsh
          echo "dir1"
          dir
          echo "release=${{ steps.gtest-tag.outputs.release }}"

      - name: Cache googleTestLatestRepo
        uses: actions/cache@v3
        with:
          path: ${{ env.strDirGTest }}
          key: cache-key-gtest-${{ steps.gtest-tag.outputs.release }}
        id: cache-gtest

      - name: Download googleTestLatestRepo
        if: steps.cache-gtest.outputs.cache-hit != 'true'
        run: | # pwsh
          git clone --depth 1 --branch ${{ steps.gtest-tag.outputs.release }} https://github.com/google/googletest.git "${{ env.strDirGTest }}"

      - name: Show log 2
        run: | # pwsh
          echo "dir1"
          dir
          echo "dir2"
          dir ${{ env.strDirGTest }}

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      # - name: Build test
        # run: MSBuild test/test.sln -noLogo -verbosity:quiet -m -p:Platform=${env:strPlatform} -p:Configuration=${env:strConfiguration} 

      # - name: Run test
        # run: | # pwsh
          # $arglist="--logfile?"
          # $strResult = Start-Process -Wait -NoNewWindow "${{env.strTestExecutable}}"
